Create workflows
blumilksoftware/e-motion-web pull request #3
Opened 2024-03-12 06:47 UTC by AleksandraKozubal

2024-04-17 18:29 UTC, Lee0z approved these changes, later dismissed

2024-04-25 06:08 UTC, kamilpiech97 requested changes
Let's remove PHP stuff
And add for `JS` type checking for `TypeScript` and run `JS` tests on pipeline.
All what u need is in `package.json`

2024-04-25 06:54 UTC, kamilpiech97 approved these changes

2024-04-25 07:25 UTC, kamilpiech97 approved these changes

2024-04-26 11:33 UTC, EwelinaSkrzypacz approved these changes

2024-04-26 11:34 UTC, merged